
# basic python programming
print("Hello ,")
print(" My name is Amey Chaudhari","\n from ECE 3rd year")
print()
print("Nice to meet you")

print("  - -  ", "  A| E | 3")
print("_-_-_-_", "  M| C | rd")
print(" <> <>", "   E| E | year")
print(" -___- ", "  Y|   ")
print("   |   ")
print(" ----- ")
print("|  |  | ")
print("|  |  | ")
print("o  |  o  ")
print("   |   ")
print(" ----- ")
print("|     | ")
print("|     | ")
print("O     O ")
