
# basic python programming
print("Hello ,")
print(" My name is Amey Chaudhari","\n from ECE")
print()
print("Nice to meet you")

print("  - -  ", "  A| E ")
print("_-_-_-_", "  M| C ")
print(" <> <>", "   E| E |")
print(" -___- ", "  Y|   ")
print("   |   ")
print(" ----- ")
print("|  |  | ")
print("|  |  | ")
print("o  |  o  ")
print("   |   ")
print(" ----- ")
print("|     | ")
print("|     | ")
print("O     O ")
